"""'test'

Revision ID: 543746027d1f
Revises: 6734b233668a
Create Date: 2023-02-04 22:28:40.444865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543746027d1f'
down_revision = '6734b233668a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
