"""'back_populates'

Revision ID: 6734b233668a
Revises: bd029c41b79e
Create Date: 2023-02-04 17:18:38.724215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6734b233668a'
down_revision = 'bd029c41b79e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
